name: Continous Integration
on: push
env: 
  DbName: Assessment
  DbUser: root
  DbPassword: Oraplus@123
jobs: 
 run_code_checks:
    runs-on: ubuntu-latest
    steps:
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        sudo mysql -e 'ALTER USER "${{env.DbUser}}"@"localhost" IDENTIFIED BY "${{env.DbPassword}}";' -uroot -proot
        sudo mysql -e 'CREATE DATABASE ${{env.DbName}};' -u${{env.DbUser}} -p${{env.DbPassword}}
    - name: Checkout Repo Code
      uses: actions/checkout@v3
    - name: Set Up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18.1
    - name: Run linting
      run: |
        go fmt ./...
        go vet ./...
    - name: run tests
      run: go test

  
