name: Continous Integration
on: push
env: 
  DB_NAME: test1
  Db_USER: root
  DB_PASSWORD: Oraplus@123
jobs: 
 run_code_checks:
    runs-on: ubuntu-latest
    steps:
    - name: Create test1 database
      run: |
        sudo mysql -e 'ALTER USER "${{env.Db_USER}}"@"localhost" IDENTIFIED BY "${{env.DB_PASSWORD}}";' -uroot -proot
        sudo mysql -u${{env.Db_USER}}  -p${{env.DB_PASSWORD}} < databases/tracker/create_databases.sql
    - name: Checkout Repo Code
      uses: actions/checkout@v2
    - name: Set Up Go
      uses: Actions/setup-go@v2
      with:
        go-version: 1.18.1
    - name: Run linting
      run: |
        go fmt ./...
        go vet ./...
    - name: run tests
      run: go test1

  
